### ISSUE TITLE
Gem conflict

### ISSUE THREAD

**Issue by cynamonium** [flowdock/capistrano-flowdock#11]
Tried to use your gem but it does not work with paperclip:

    Fetching gem metadata from https://rubygems.org/........
    Resolving dependencies...
    Bundler could not find compatible versions for gem "mime-types":
    In Gemfile:
    capistrano-flowdock (>= 0) ruby depends on
      grit (~> 2.4) ruby depends on
        mime-types (~> 1.15) ruby

    paperclip (~> 4.2) ruby depends on
      mime-types (2.4.3)

    Bundler could not find compatible versions for gem "capistrano":
    In Gemfile:
      capistrano-flowdock (>= 0) ruby depends on
        capistrano (~> 2.0) ruby

    capistrano (3.3.5)

Rails 4.2, ruby 2.1.5, capistrano 3.3.5

**Comment by lautis** [comment]
I pushed out a new version out that uses rugged instead of grit. This should fix the dependency conflict with paperclip.

**Comment by cynamonium** [comment]
that was fast :+1:  and it works ;)
